core/monster-manual.index
core/monster-manual/lycanthropy-additional-feature.xml

Added MM Lycanthropy as an Additional Feature

Monster Manual: Lycanthropy

---

core.index
core/internal.xml
core/sources.xml
supplements/tashas-cauldron-of-everything.index
supplements/tashas-cauldron-of-everything/options.xml

• removes "sources.xml" from core.index and adds "internal.xml" in.
• small restructure of the TCOE index and addition of "options.xml".
• Options themselves are temporarily commented out.

[TCOE] pre-Part 2

---

core/players-handbook/races/race-halforc.xml

Version issue on race-halforc.xml causing people to not get new version

[MISC] Fix race-halforc.xml

---

core/players-handbook/feats.xml

Co-Authored-By: @AngryGuineaPig

[PHB] Tough Feat Fix

---

supplements/waterdeep-dungeon-of-the-mad-mage/items.xml

[WDMM] Shield of the Uven Rune attunement fix

---

supplements/eberron-rising-from-the-last-war/races/orc.xml

Found several instances of zeroes and "ores" in the description. No mechanical changes are included.
You can ping me on Discord as draxios#9833 if there are any questions.

[ERLW] Fixed typos in ERLW orc.xml

---

core/internal.xml
supplements/eberron-rising-from-the-last-war/class-artificer.xml

This pull fixes issue #43 
Created mostly by: @GameDevNet

[MISC] Fixed issue with Artificer Multiclass Slots not rounding up

---

unearthed-arcana.index
unearthed-arcana/2021/20210126.xml
unearthed-arcana/2021/20210311.xml

> Wander into the magical realm of the Feywild in this month’s Unearthed Arcana! With the playtest options in the PDF below, your D&D character can be a member of one of these new D&D races: fairy, hobgoblin of the Feywild, owlfolk, or rabbitfolk.

[UA] 20210311: Folk of the Feywild

---

supplements/xanathars-guide-to-everything/archetypes/sorcerer-divinesoul.xml

[XGTE] Enable swapping of Divine Magic Spell

---

core/internal.xml
unearthed-arcana.index
unearthed-arcana/2021/20210311.xml
unearthed-arcana/2021/20210414.xml

• includes ASI Options for internal.xml
• and update for UA: Folk of the Feywild with proper ASI Option select.

[UA] 20210414: Draconic Options

---

unearthed-arcana.index
unearthed-arcana/2021/20210608.xml

Base Structure by @eterean
Editing and Formatting by @NickVendel

[UA] 20210608: Mages of Strixhaven

---

supplements/eberron-rising-from-the-last-war/class-artificer.xml

closes #78
Companion code by: @stgreenb

Add Homunculus Servant Companion and Statblock

---

supplements/tashas-cauldron-of-everything/archetypes/druid-wildfire.xml

- Added and corrected the Wildfire Spirit Statblock.
- Stopped the companion from being automatically granted.
- Minor spelling fixes
- Replacement OCF Support

[TCOE] Wildfire improvements

---

supplements/explorers-guide-to-wildemount/archetypes/wizard-chronurgy.xml
supplements/explorers-guide-to-wildemount/items.xml

[EGtW] typos and fixes

---

supplements/mythic-odysseys-of-theros/items.xml

Fixed Rarities on Pyxis and Helm
Added missing attunement on Helm

[MOoT] Item Corrections

---

supplements/tashas-cauldron-of-everything/feats.xml
supplements/van-richtens-guide-to-ravenloft/race-hexblood.xml
supplements/wild-beyond-the-witchlight/race-fairy.xml
unearthed-arcana/2020/20200414.xml
unearthed-arcana/2020/20200713.xml
unearthed-arcana/2021/20210126.xml
unearthed-arcana/2021/20210311.xml
unearthed-arcana/2021/20210414.xml
unearthed-arcana/2021/20211008.xml

Full details under first commit - https://github.com/AuroraLegacy/elements/commit/5335b1baf5ce0daa90d7332d819c9a5ce9d2c681
For easy testing you can unpack following [archive with changes](https://github.com/AuroraLegacy/elements/files/7383020/changes.zip) to your custom/user folder.

[MISC] Removal of inline stats

---

supplements/strixhaven-a-curriculum-of-chaos.index
supplements/strixhaven-a-curriculum-of-chaos/items.xml

magic items are not correctly being downloaded

[SCOC] Index fix

---

unearthed-arcana.index
unearthed-arcana/2022/20220308.xml
unearthed-arcana/2022/20220425.xml

Additionally includes fixes for previous UA, details are in the 8e55913094254f6b6dd2c564ca6ad0da5981a53a commit.

[UA] 20220425: Heroes of Krynn Revisited

---

supplements/curse-of-strahd/items.xml

[CoS] Sunsword Missing Bonus and Info

---

core/players-handbook/classes/class-bard.xml
supplements/monsters-of-the-multiverse/race-harengon.xml
supplements/wild-beyond-the-witchlight/race-harengon.xml

[MISC] Haregnon, Jack of All Trades Fix 

---

supplements/xanathars-guide-to-everything/spells.xml

casting time now reads "1 action"
solves #162

[XGtE| - Mental Prison typo

---

supplements/tashas-cauldron-of-everything/artificer-infusions.xml

Recommending changes for Arcane Propulsion Armor, and Armor of Magical Strength, so they aren't listed improperly as common.

[TCOE] Artificer Infusion Item Rarity 

---

core/dungeon-masters-guide/items/items-wondrous.xml
supplements/acquisitions-incorporated/items.xml
supplements/explorers-guide-to-wildemount/items.xml
supplements/xanathars-guide-to-everything/archetypes/ranger-gloomstalker.xml
unearthed-arcana/2019/20191017.xml

[MISC] Darkvision or Increased Range Fixes

---

core/players-handbook/classes/class-cleric.xml
core/players-handbook/classes/class-wizard.xml
core/players-handbook/spells.xml

Issue: https://github.com/AuroraLegacy/elements/issues/193

[PHB] Missing Header Class Table for Wizard

---

core/monster-manual/companions.xml
supplements.index
supplements/fizbans-treasury-of-dragons/archetypes/ranger-drakewarden.xml
supplements/fizbans-treasury-of-dragons/feats.xml
supplements/glory-of-the-giants.index
supplements/glory-of-the-giants/backgrounds/background-giant-foundling.xml
supplements/glory-of-the-giants/backgrounds/background-rune-carver.xml
supplements/glory-of-the-giants/barbarian-giant.xml
supplements/glory-of-the-giants/feats.xml
supplements/glory-of-the-giants/items-magic.xml
supplements/glory-of-the-giants/source.xml

details are in the first commit.

[GOTG] Bigby Presents: Glory of the Giants + Fixes

---

core/players-handbook/spells.xml

Adjusted Casting Time of Wind Walk from 1 action to 1 minute (PHB page 288)

Corrected Casting Time of Wind Walk

---

supplements/volos-guide-to-monsters/race-triton.xml

This spell is also present in [spells.xml](https://github.com/AuroraLegacy/elements/blob/master/supplements/volos-guide-to-monsters/spells.xml), with the same ID but with fewer spelling errors.

[VGTM] Remove a duplicate "Wall of Water" spell
